---
- name: Install spamassassin packages
  apt:
    name: "{{ sa__default_packages }}"
    update_cache: yes
    state: present
  when:
    - sa__install

- name: Enable spamassassin
  systemd:
    name: spamd
    state: started
    enabled: yes
  when:
    - sa__install
    - sa__configure

- name: Setup default file
  template:
    src: spamd
    dest: /etc/default/spamd
    owner: root
    group: root
    mode: 0644
  when:
    - sa__install
    - sa__configure

- name: Mark subjects
  lineinfile:
    regexp: "^# rewrite_header"
    line: 'rewrite_header Subject ***SPAM***'
    path: /etc/spamassassin/local.cf
  notify: Reload spamassassin
  when:
    - sa__install
    - sa__configure

- name: Change score
  lineinfile:
    regexp: "^# required_score"
    line: 'required_score 4.0'
    path: /etc/spamassassin/local.cf
  notify: Reload spamassassin
  when:
    - sa__install
    - sa__configure
